### ISSUE TITLE
No db schema

### ISSUE THREAD

**Issue by walix** [turtles2/WISPBill#1]
Hi,

I would like to try this app but can not find the schema of the database

Thanks & Regards

**Comment by turtles2** [comment]
Basic Features are still in Development I hope to have both Radius and UBNT device support (Firewall/QOS SSH control will do auto shutoff) for billing by the end of the month. As of now they are not there yet. The DB is constantly changing as I make adjustments. If you still want I can throw it up here. What do you want to use this app for?

**Comment by walix** [comment]
I have a small wisp and I would like to work with this.

**Comment by turtles2** [comment]
I understand. I will make a commit with it soon. To run this your PHP needs mcrypt and if you intend to use the Airos Poller you will also need php ssh2 there may be others but nothing comes to mind. My DEV environment is Ubuntu 14.04 LTS with Apache and MySQL. SSL is required. I will also post a Readme with basic set up instructions.

**Comment by turtles2** [comment]
Solved please start a new issue for install help

**Comment by turtles2** [comment]
FYI this project has moved to [here](https://github.com/WISPBill)
